language: haxe

os:
  - linux

haxe:
  - "3.4.7"
  - "4.0.0"
  - development

matrix:
  allow_failures:
    - haxe: "3.4.7"
    - haxe: development

install:
  - haxelib dev three.hx .

script:
  - haxe haxedoc.hxml
  - haxe --cwd examples/basic build.hxml
  - haxe --cwd examples/hello build.hxml
