sudo: required
dist: trusty

language: haxe

os:
  - linux

haxe:
  - "3.4.3"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib dev three.hx .

script:
  - haxe doc.hxml
