language: haxe

os:
  - linux

haxe:
  - "3.4.7"
  - development

matrix:
  allow_failures:
    - haxe: "3.4.7"

install:
  - haxelib dev three.hx .

script:
  - haxe haxedoc.hxml
  - haxe --cwd examples/basic build.hxml
  - haxe --cwd examples/hello build.hxml
